using UnityEngine;
using UnityEngine.UI;

public class UIManager:MonoBehaviour {
    public static UIManager I{get;private set;}
    Canvas canvas; Text title,info;
    Button play,retry,next,menu,pause;
    void Awake(){I=this;DontDestroyOnLoad(gameObject);Build();}
    Text Label(string s,int size){var g=new GameObject("Text");g.transform.SetParent(canvas.transform,false);var t=g.AddComponent<Text>();t.text=s;t.font=Resources.GetBuiltinResource<Font>("Arial.ttf");t.fontSize=size;t.alignment=TextAnchor.MiddleCenter;t.color=Color.white;return t;}
    Button Btn(string s,float y){var g=new GameObject(s);g.transform.SetParent(canvas.transform,false);var r=g.AddComponent<RectTransform>();r.anchorMin=new Vector2(.2f,y);r.anchorMax=new Vector2(.8f,y+.08f);r.offsetMin=r.offsetMax=Vector2.zero;var img=g.AddComponent<Image>();img.color=new Color(.05f,.42f,.95f,.95f);var b=g.AddComponent<Button>();b.targetGraphic=img;var t=Label(s,28);t.transform.SetParent(g.transform,false);t.rectTransform.anchorMin=Vector2.zero;t.rectTransform.anchorMax=Vector2.one;t.rectTransform.offsetMin=t.rectTransform.offsetMax=Vector2.zero;return b;}
    void Build(){var g=new GameObject("Canvas");canvas=g.AddComponent<Canvas>();canvas.renderMode=RenderMode.ScreenSpaceOverlay;var sc=g.AddComponent<CanvasScaler>();sc.uiScaleMode=CanvasScaler.ScaleMode.ScaleWithScreenSize;sc.referenceResolution=new Vector2(1080,1920);g.AddComponent<GraphicRaycaster>();title=Label("GOAL RUSH 3D",56);title.rectTransform.anchorMin=new Vector2(.05f,.82f);title.rectTransform.anchorMax=new Vector2(.95f,.95f);title.rectTransform.offsetMin=title.rectTransform.offsetMax=Vector2.zero;info=Label("",28);info.rectTransform.anchorMin=new Vector2(.05f,.68f);info.rectTransform.anchorMax=new Vector2(.95f,.80f);info.rectTransform.offsetMin=info.rectTransform.offsetMax=Vector2.zero;play=Btn("PLAY",.48f);retry=Btn("RETRY",.36f);next=Btn("NEXT LEVEL",.48f);menu=Btn("MAIN MENU",.24f);pause=Btn("PAUSE",.88f);play.onClick.AddListener(()=>GameManager.I.StartLevel(SaveSystem.Data.level));retry.onClick.AddListener(()=>GameManager.I.Retry());next.onClick.AddListener(()=>GameManager.I.NextLevel());menu.onClick.AddListener(()=>{HideEnd();GameManager.I.SetState(GameState.MainMenu);});pause.onClick.AddListener(()=>GameManager.I.Pause());HideEnd();}
    void HideEnd(){retry.gameObject.SetActive(false);next.gameObject.SetActive(false);menu.gameObject.SetActive(false);}
    void Update(){if(GameManager.I==null)return;bool main=GameManager.I.State==GameState.MainMenu;bool playState=GameManager.I.State==GameState.Playing;play.gameObject.SetActive(main);pause.gameObject.SetActive(playState);if(main){title.text="GOAL RUSH 3D";info.text=$"Coins {SaveSystem.Data.coins}   Gems {SaveSystem.Data.gems}\nLevel {SaveSystem.Data.level}/100";}if(playState&&PlayerController.I!=null)info.text=$"❤ {PlayerController.I.Health}    🪙 {PlayerController.I.CoinsCollected}    SCORE {PlayerController.I.Score}";}
    public void ShowComplete(int score,int money,int coins,int stars){title.text="LEVEL COMPLETE!";info.text=$"Score {score}\nCoins {coins}   Bonus {money}   ⭐ {stars}";play.gameObject.SetActive(false);pause.gameObject.SetActive(false);next.gameObject.SetActive(true);menu.gameObject.SetActive(true);}
    public void ShowGameOver(){title.text="GAME OVER";info.text=$"Score {PlayerController.I.Score}";play.gameObject.SetActive(false);pause.gameObject.SetActive(false);retry.gameObject.SetActive(true);menu.gameObject.SetActive(true);}
}
